version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vacancies_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/vacancies_db
    depends_on:
      - db

volumes:
  postgres_data: